spring:
  application:
    name: dataset-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/stattlabDB

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        fileUploaded-out-0:
          destination: file_uploaded
          content-type: application/json
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: datasets

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
